### ISSUE TITLE
mobilenet SSD on raspberry pi

### ISSUE THREAD

**Issue by 3073** [PINTO0309/MobileNet-SSD-RealSense#1]
Hi there !! 
I have SSD mobile net model (written in tensorflow) for image classification..... and it works well on my windows pc with a dlib tracker added to it..... but i need to use a raspberry pi for prototyping ... 
i install tensorflow on my RPi and try to execute the file ( on the python 3 IDLE) and it shows me nothing but no error is generated.... could you tell me my mistake ?

**Comment by PINTO0309** [comment]
@3073 
Since it is the same content, I would like to discuss with the issue below.
https://github.com/PINTO0309/MobileNet-SSD/issues/1
