### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dorodnic** [PINTO0309/MobileNet-SSD-RealSense#27]
Hi @PINTO0309 
This is such an amazing work! May I link to it from [librealsense/examples#community-projects](https://github.com/IntelRealSense/librealsense/tree/master/examples#community-projects)?

**Comment by PINTO0309** [comment]
Please use it freely.
I'm a member of Intel's Innovator Program, so I'm publishing the project below.
**https://devmesh.intel.com/projects/real-time-object-detection-by-combination-of-depth-camera-and-vpu-implementation-of-high-speed-transparentation-and-distance-measurement**

**Comment by dorodnic** [comment]
Thanks! 
Very impressive project. Please ping me via email if you have any suggestions / issues / ideas regarding RealSense.
