### ISSUE TITLE
Delay problem

### ISSUE THREAD

**Issue by 107318095** [PINTO0309/MobileNet-SSD-RealSense#32]
Why the position displayed by the detection frame is not the position of the instant picture, he will probably be slower by 3~5 frames.

**Comment by PINTO0309** [comment]
Since multiprocessing is performed completely asynchronously with shooting and inference, the frame will be misaligned. Use SingleStickSSDwithUSBCamera_OpenVINO_NCS2.py if the problem is that the frame is misaligned. The frame is not misaligned because it is a complete synchronization process.
